# Generated by Django 5.1 on 2024-08-26 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='mark_all_as_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='route',
            field=models.ForeignKey(default='No Route', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.route'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default='No Seats', on_delete=django.db.models.deletion.SET_DEFAULT, to='main.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='main.bus'),
        ),
    ]
