# Generated by Django 5.1 on 2024-08-26 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_passenger_part_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
